const serviceData = [
    {
      id: 1,
      image: "Services/images/service-hero-bg.jpg",
      title: "Our Services",
      shortDescription: "Our mission is to engage in issues that are of concern to individuals",
    },
    {
        id: 2,
        image: "Services/images/it-consultancy.jpg",
        title: "IT Consultancy",
        icon: "Services/icons/it-consultancy-icon.jpg",
        shortDescription: "We believe that technology design are revolutionizing brand experiences.",
        heading: "Tuning in to what really matters",
        mainDescription: "We believe that technology and human-centered design are revolutionizing brand experiences. Remarkable innovations are allowing products to become more sentient and connected, enabling greater connection between people. Our role is to ensure that each product experience is attuned to people’s needs and relevant to the rhythm and habits of their daily lives. Through first and secondary research, we identify what will really matter to users and we never let go of the vision that inspires great products.",
    },
    {
        id: 3,
        image: "Services/images/cloud-migration.jpg",
        title: "Cloud Migration",
        icon: "Services/icons/cloud-migration-icon.jpg",
        shortDescription: "Process of designing, creating, deploying and maintaining software.",
        heading: "Tuning in to what really matters",
        mainDescription: "We believe that technology and human-centered design are revolutionizing brand experiences. Remarkable innovations are allowing products to become more sentient and connected, enabling greater connection between people. Our role is to ensure that each product experience is attuned to people’s needs and relevant to the rhythm and habits of their daily lives. Through first and secondary research, we identify what will really matter to users and we never let go of the vision that inspires great products.",
    },
    {
        id: 4,
        image: "Services/images/poc-development.jpg",
        title: "PoC Development",
        icon: "Services/icons/poc-development-icon.jpg",
        shortDescription: "Protect networks, devices and data from attacks or unauthorized access.",
        heading: "Tuning in to what really matters",
        mainDescription: "We believe that technology and human-centered design are revolutionizing brand experiences. Remarkable innovations are allowing products to become more sentient and connected, enabling greater connection between people. Our role is to ensure that each product experience is attuned to people’s needs and relevant to the rhythm and habits of their daily lives. Through first and secondary research, we identify what will really matter to users and we never let go of the vision that inspires great products.",
    },
    {
        id: 5,
        image: "Services/images/smart-team.jpg",
        title: "Smart Team",
        icon: "Services/icons/smart-team-icon.jpg",
        shortDescription: "See to the integrity and security of your records.",
        heading: "Tuning in to what really matters",
        mainDescription: "We believe that technology and human-centered design are revolutionizing brand experiences. Remarkable innovations are allowing products to become more sentient and connected, enabling greater connection between people. Our role is to ensure that each product experience is attuned to people’s needs and relevant to the rhythm and habits of their daily lives. Through first and secondary research, we identify what will really matter to users and we never let go of the vision that inspires great products.",
    },
    {
        id: 6,
        image: "Services/images/quality-assurance.jpg",
        title: "Quality Assurance",
        icon: "Services/icons/quality-assurance-icon.jpg",
        shortDescription: "See to the integrity and security of your records.",
        heading: "Tuning in to what really matters",
        mainDescription: "We believe that technology and human-centered design are revolutionizing brand experiences. Remarkable innovations are allowing products to become more sentient and connected, enabling greater connection between people. Our role is to ensure that each product experience is attuned to people’s needs and relevant to the rhythm and habits of their daily lives. Through first and secondary research, we identify what will really matter to users and we never let go of the vision that inspires great products.",
    },
    {
        id: 7,
        image: "Services/images/product-design.jpg",
        title: "Product Design",
        icon: "Services/icons/product-design-icon.jpg",
        shortDescription: "See to the integrity and security of your records.",
        heading: "Tuning in to what really matters",
        mainDescription: "We believe that technology and human-centered design are revolutionizing brand experiences. Remarkable innovations are allowing products to become more sentient and connected, enabling greater connection between people. Our role is to ensure that each product experience is attuned to people’s needs and relevant to the rhythm and habits of their daily lives. Through first and secondary research, we identify what will really matter to users and we never let go of the vision that inspires great products.",
    },
]